USE project4-db;

CREATE TABLE PRODUCT (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(40) NOT NULL,
    QUANTITY INT NOT NULL,
    CATEGORY VARCHAR(40) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CONSTRAINT pk_constraint PRIMARY KEY(id)
);